-- 코드를 입력하세요
# SELECT CART_ID
# FROM(
#     SELECT ID, CART_ID
#     FROM CART_PRODUCTS
#     GROUP BY CART_ID, NAME
#     HAVING NAME IN ("Milk", "Yogurt")
#     ) AS PRODUCT
# GROUP BY PRODUCT.CART_ID
# HAVING COUNT(PRODUCT.ID)=2
# ORDER BY CART_ID

SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) = 2
ORDER BY CART_ID

# 286
# 448	
# 578	
# 977	
# 1048