-- 코드를 입력하세요
SELECT YEAR(SALE.SALES_DATE) AS YEAR, MONTH(SALE.SALES_DATE) AS MONTH, INFO.GENDER AS GENDER, COUNT(DISTINCT SALE.USER_ID) AS USERS
FROM ONLINE_SALE AS SALE
    JOIN USER_INFO AS INFO
    ON SALE.USER_ID = INFO.USER_ID
GROUP BY YEAR(SALE.SALES_DATE), MONTH(SALE.SALES_DATE), INFO.GENDER
HAVING INFO.GENDER IS NOT NULL
ORDER BY 1,2,3

# SELECT YEAR(SALES_DATE)YEAR, MONTH(SALES_DATE)MONTH, GENDER,COUNT( i.USER_ID)USERS
# FROM USER_INFO as i,ONLINE_SALE as o
# WHERE i.USER_ID = o.USER_ID
# AND GENDER is not null
# GROUP BY 1,2,3
# ORDER BY 1,2,3