-- 코드를 작성해주세요
SELECT QUARTER, COUNT(ID) AS ECOLI_COUNT
FROM
    (SELECT ID, CASE WHEN MONTH(DIFFERENTIATION_DATE)<=3 THEN "1Q"
         WHEN MONTH(DIFFERENTIATION_DATE)<=6 THEN "2Q"
         WHEN MONTH(DIFFERENTIATION_DATE)<=9 THEN "3Q"
         ELSE "4Q" END AS QUARTER
    FROM ECOLI_DATA) AS Q
GROUP BY Q.QUARTER
ORDER BY 1