-- 코드를 입력하세요
# SELECT HISTORY.HISTORY_ID, ROUND(DAILY_FEE * (DATEDIFF(END_DATE,START_DATE)+1)*(100-DISCOUNT_RATE)/100,0) AS DAILY_FEE
# , DATEDIFF(END_DATE,START_DATE)+1, DISCOUNT_RATE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
#     JOIN CAR_RENTAL_COMPANY_CAR  AS CAR
#     ON HISTORY.CAR_ID = CAR.CAR_ID
#     , CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN
# WHERE CAR.CAR_TYPE="트럭" AND PLAN.CAR_TYPE="트럭" AND

SELECT A.HISTORY_ID,
    IF(DISCOUNT_RATE IS NULL, A.RENT_DAY*DAILY_FEE, FLOOR(A.RENT_DAY*DAILY_FEE*(100-DISCOUNT_RATE)/100)) AS FEE
FROM(
    SELECT HISTORY.HISTORY_ID, DATEDIFF(END_DATE,START_DATE)+1 AS RENT_DAY, CAR.DAILY_FEE,
    CASE
        WHEN DATEDIFF(END_DATE,START_DATE)+1 >=90 THEN "90일 이상"
        WHEN DATEDIFF(END_DATE,START_DATE)+1 >=30 THEN "30일 이상"
        WHEN DATEDIFF(END_DATE,START_DATE)+1 >=7 THEN "7일 이상"
        ELSE "7일 이하"
    END AS DAY
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
        JOIN CAR_RENTAL_COMPANY_CAR  AS CAR
        ON HISTORY.CAR_ID = CAR.CAR_ID
    WHERE CAR.CAR_TYPE="트럭") AS A
    LEFT JOIN (SELECT DURATION_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE CAR_TYPE="트럭") AS B
    ON A.DAY = B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC