-- 코드를 입력하세요
SELECT APNT_NO,	PT_NAME, PATIENT .PT_NO, DOCTOR.MCDP_CD, DR_NAME, APNT_YMD
FROM APPOINTMENT
    JOIN DOCTOR
    ON APPOINTMENT.MDDR_ID = DOCTOR.DR_ID
    JOIN PATIENT 
    ON PATIENT .PT_NO = APPOINTMENT.PT_NO
WHERE APNT_YMD LIKE "2022-04-13 %" AND APNT_CNCL_YN = "N" AND DOCTOR .MCDP_CD = "CS"
ORDER BY APNT_YMD