-- 코드를 입력하세요
# SELECT HOUR(DATETIME), COUNT(ANIMAL_ID) AS COUNT
# FROM ANIMAL_OUTS
# GROUP BY HOUR(DATETIME)
# ORDER BY HOUR(DATETIME)

WITH recursive TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME WHERE HOUR<23)

SELECT TIME.HOUR AS HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS as OUTS
    RIGHT JOIN TIME
on HOUR(OUTS.DATETIME) = TIME.hour
GROUP BY 1
ORDER BY 1