-- 코드를 작성해주세요
# SELECT *
# FROM HR_EMPLOYEES

SELECT EMP.EMP_NO,	EMP.EMP_NAME,	GRADE,
    CASE WHEN GRADE ="S" THEN SAL*0.2
        WHEN GRADE = "A" THEN SAL*0.15
        WHEN GRADE = "B" THEN SAL*0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES AS EMP,
    (SELECT EMP_NO,
        CASE
            WHEN SUM(SCORE)/2 >= 96 THEN "S"
            WHEN SUM(SCORE)/2 >= 90 THEN "A"
            WHEN SUM(SCORE)/2 >= 80 THEN "B"
            ELSE "C"
        END AS GRADE
    FROM HR_GRADE
    GROUP BY EMP_NO) AS GRADE
WHERE EMP.EMP_NO = GRADE.EMP_NO
ORDER BY 1