-- 코드를 입력하세요
# SELECT PRO.MEMBER_NAME, REV.REVIEW_TEXT, REV.REVIEW_DATE
# FROM MEMBER_PROFILE AS PRO
#     JOIN REST_REVIEW AS REV
#     ON PRO.MEMBER_ID = REV.MEMBER_ID
# WHERE PRO.MEMBER_ID IN
#     (SELECT MEMBER_ID
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
#     ORDER BY COUNT(REVIEW_ID) DESC)

SELECT PRO.MEMBER_NAME, REV.REVIEW_TEXT, DATE_FORMAT(REV.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS REV
    JOIN MEMBER_PROFILE AS PRO
    ON PRO.MEMBER_ID = REV.MEMBER_ID
WHERE REV.MEMBER_ID IN (
    SELECT RANKING.MEMBER_ID FROM (
        SELECT RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) AS "RANKING", MEMBER_ID
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) AS RANKING
    WHERE RANKING = 1)
ORDER BY 3, 2


# SELECT PRO.MEMBER_NAME, REV.REVIEW_TEXT, DATE_FORMAT(REV.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
# FROM REST_REVIEW AS REV
#     JOIN MEMBER_PROFILE AS PRO
#     ON PRO.MEMBER_ID = REV.MEMBER_ID
# WHERE REV.MEMBER_ID IN ("jihoon93@hanmail.net", "jimin88@naver.com", "yeahjin98@nate.com")

# SELECT *
# FROM REST_REVIEW
# WHERE MEMBER_ID IN (
#     SELECT RANKING.MEMBER_ID FROM (
#             SELECT RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) AS "RANKING", MEMBER_ID
#             FROM REST_REVIEW
#             GROUP BY MEMBER_ID) AS RANKING
#         WHERE RANKING = 1)

# SELECT RANKING.MEMBER_ID FROM (
#         SELECT RANK() OVER (ORDER BY COUNT(REVIEW_ID) DESC) AS "RANKING", MEMBER_ID
#         FROM REST_REVIEW
#         GROUP BY MEMBER_ID) AS RANKING
#     WHERE RANKING = 1

# MEMBER_ID
# ksjs1115@gmail.com
# soso94@naver.com
# minjea985@naver.com
