-- 코드를 작성해주세요
# SELECT YEAR(DIFFERENTIATION_DATE), MAX(SIZE_OF_COLONY) AS MAX_SIZE
# FROM ECOLI_DATA
# GROUP BY YEAR(DIFFERENTIATION_DATE)

SELECT YEAR, MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA,
    (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)) AS M
WHERE YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY 1,2