-- 코드를 작성해주세요

SELECT SCORE.SCORE, SCORE.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES AS EMP, (
    SELECT SUM(SCORE) AS SCORE, EMP_NO
    FROM HR_GRADE
    GROUP BY EMP_NO, YEAR
    HAVING YEAR = "2022"
    ORDER BY 1 DESC
    LIMIT 1) AS SCORE
WHERE EMP.EMP_NO = SCORE.EMP_NO

# SELECT SUM(SCORE) AS SCORE, EMP_NO
# FROM HR_GRADE
# GROUP BY EMP_NO, YEAR
# HAVING YEAR = "2022"
# ORDER BY 1 DESC
# LIMIT 1
