-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",FILE.BOARD_ID,"/", FILE.FILE_ID,FILE.FILE_NAME,FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS FILE
JOIN (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
) AS BOARD
ON FILE.BOARD_ID = BOARD.BOARD_ID
ORDER BY FILE.FILE_ID DESC
